### PR TITLE
Update serde and serde_json to Version 1. Also be less restrictive.

### PR DESCRIPTION
**Pull request by Manuel-K**

### CODE REVIEW

**Comment by Manuel-K** [comment]
Doesn't work because an error message was changed. That's bad.

**Comment by Manuel-K** [comment]
The error message was changed before the release of version 0.9.7: https://github.com/serde-rs/json/commit/9b0010c5a324e592dfc7cd8d4adf40982282d083

**Comment by lynxlynxlynx** [comment]
Any particular benefit of the bump? LGTM otherwise.

**Comment by Manuel-K** [comment]
We were forcing rust to use specific outdated versions of both libraries.

I don't see a reason to do that unless there is a specific bug that forces us to do so.

**Comment by Manuel-K** [comment]
These changes (or similar changes) are included in #548

**Pull request merged**
