### PR TITLE
github-ci: macos-12 is getting sunset, switch to latest

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
Trivial stuff, one other cases is already using this runner.

### CODE REVIEW

**Comment by momoko-h** [comment]
This would also change the architecture from Intel to ARM, so the artifacts produced by this Runner would no longer work on older Macs, right? Do we care about that? Of course, sooner or later the last Intel-compatible version of MacOS will no longer be supported by Github anyway.

Also noteworthy: since this required a full rebuilt sccache's hit ratio was 0% but the build still needed only 6 minutes to complete. Do we even need it?

**Comment by lynxlynxlynx** [comment]
Yes, we could switch to -13 while it's still available, but -14 is already M1+. I have no idea which users would be upset more, since we here from apple fans so rarely, so I went for the pragmatic choice.

As for sccache, it probably still saves some upstream resources.

**Comment by momoko-h** [comment]
That's true, I also have no idea whether Mac users would prefer support for older machines or native builds for their more recent systems. Maybe someone else could chime in with some insights.

**Comment by momoko-h** [comment]
Alternative idea: how about having two MacOS runners, one MacOS 13 for Intel, one -latest for ARM? To make this a bit more useful, one of them could exercise some CMake options we're currently not testing, for example WITH_MAGICENUM=OFF or WITH_MAEMO=ON.

**Comment by lynxlynxlynx** [comment]
Apparently recent macos versions don't even report their version correctly, so there's no usable market share data.
A compromise would be to remain on latest, but also build releases for x86.

**Comment by selaux** [comment]
Question is whether anyone in the team can even test macOS x86 anymore. I can test at least the ARM version again, as I have a machine available, but I don't have a x86 mac anymore. With the current x86 build, I can at least test through the macOS compatibility layer. Not sure if it would make sense to push out a build that has not, at least, been started up once to check whether it works properly.

NB: For the universal build, we would also need to check whether all of the libraries (including the rust stuff) could be built universally.

**Comment by lynxlynxlynx** [comment]
I agree and from previous experience, making fat builds is not easy. Even MSP hosts separate builds. Anyway, any objection to merging?

**Comment by momoko-h** [comment]
No, let's go ahead. We'll see if we get some reaction from Intel Mac users.

**Pull request merged**
