### PR TITLE
Do no update sight values in DecaySmokeEffects and DecayLightEffects

### PR DESCRIPTION
**Pull request by momoko-h**
Let the callers of these functions call AllTeamsLookForAll themselves when
they need to.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
I think it would be more robust and DRY if you added a defaulted optional param and called with it set to false from TrashWorld, the only other real user.

**Comment by momoko-h** [comment]
Here is the alternative version, in case you prefer this way.

**Comment by lynxlynxlynx** [comment]
I don't feel strongly about it, but using an argument would also make the extra work explicit. It's a pretty much finished product though, so it's hard to gauge whether we'll need to use these functions in any new places later, increasing the duplication. @selaux @ja2-derek any preferences?

**Comment by selaux** [comment]
I like the explicit version slighly better, but no strong feelings as well.

**Pull request merged**
