### PR TITLE
[WIP] Slog rust

### PR DESCRIPTION
**Pull request by selaux**
This PR allows logging via slog for rust code. It is still very much a WIP (just tried to get it to work somehow). Just wanted to know if this is something we want to have.

Implementation:

- Use `log` logging facade module in rust
- Write logger that uses a function pointer passed from C++ to execute SLOG
- Single SLOG topic for all rust messages
- For rust messages they include the module they are logging from in the message
- Slog code was converted to C++ in order to be able to use basic types for log level and topic

This would be an example log:

```
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Looking for data dir in "/home/stefan/.ja2/orig_data"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Found "/home/stefan/.ja2/orig_data/data"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Searching for resource packs in "externalized/resource_packs"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Found "externalized/resource_packs/gog_jagged_alliance_2.json"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Found "externalized/resource_packs/steam_jagged_alliance_2_classic_pl.json"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Found "externalized/resource_packs/steam_jagged_alliance_2_classic_fr.json"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Found "externalized/resource_packs/steam_jagged_alliance_2_classic_ru.json"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Found "externalized/resource_packs/steam_jagged_alliance_2_classic_de.json"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Reading "externalized/resource_packs/gog_jagged_alliance_2.json"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Got resource pack "GOG - Jagged Alliance 2 - Release v1.12 (Build 04.12.02)"
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Found vanilla_version ENGLISH
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Getting resources (no hashes)
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] with_file_size
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Found 180 resources (no hashes)
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Comparing resources (no hashes)
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Passed (no hashes), repeating with hashes
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] Getting resources
2019/04/18 16:15:24 INFO    [Rust            ] [stracciatella::guess] with_hash_md5
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found 180 resources
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Comparing resources
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Passed with 2 extra resources
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found match with vanilla_version ENGLISH
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Extra resource: "editor.slf"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Extra resource: "maps/error.dat"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] New best match
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Reading "externalized/resource_packs/steam_jagged_alliance_2_classic_pl.json"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Got resource pack "Steam - Jagged Alliance 2 Classic - Release 1.05R (Build 99.09.22) - Polish"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found vanilla_version POLISH
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Getting resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] with_file_size
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found 180 resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Comparing resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Error: resource "Bigitems.slf" not found
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Reading "externalized/resource_packs/steam_jagged_alliance_2_classic_fr.json"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Got resource pack "Steam - Jagged Alliance 2 Classic - Release 1.06 (Build 99.09.22) - French"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found vanilla_version FRENCH
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Getting resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] with_file_size
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found 180 resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Comparing resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Error: resource "BIGITEMS.SLF" not found
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Reading "externalized/resource_packs/steam_jagged_alliance_2_classic_ru.json"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Got resource pack "Steam - Jagged Alliance 2 Classic - Release 1.06 (Build 99.12.07) - Russian"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found vanilla_version RUSSIAN
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Getting resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] with_file_size
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found 180 resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Comparing resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Error: resource "BATTLESNDS.SLF" not found
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Reading "externalized/resource_packs/steam_jagged_alliance_2_classic_de.json"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Got resource pack "Steam - Jagged Alliance 2 Classic - Release 1.02 (Build 99.06.11) - German"
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found vanilla_version GERMAN
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Getting resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] with_file_size
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Found 180 resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Comparing resources (no hashes)
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Error: resource "BIGITEMS.SLF" not found
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] No more resource packs
2019/04/18 16:15:26 INFO    [Rust            ] [stracciatella::guess] Using best match with vanilla_version ENGLISH
```

### CODE REVIEW

**Comment by flaviojs** [comment]
Another alternative is to redirect slog to rust log?
Rust would receive the the tag name (target) and the result of snprintf (message).

**Comment by selaux** [comment]
Yes, that would be the other way. Basically that would get rid of SLOG alltogether. It would add ffi overhead to each log call from C++ though, and as we have much more of them I opted to go the other way. I dont know how much impact that would have in practice, but the C++ log calls are in more performance sensitive areas than the rust log calls currently. What do you think?

**Comment by flaviojs** [comment]
During logging a bit more code is negligible in comparison to the cost of writing to file or console so performance isn't an issue, and if the log crate is capable of asynchronous logging you already have an improvement.

For ignored log messages performance matters more so you can just give rust a static lifetime variable to manage and use it instead of s_consoleLevel/s_fileLevel. It would reduce the number of comparisons needed to reject a log message in C++.

PS- My last PR was my first contact with rust and I really liked it. Is there some code that you want rustified? It would be a productive way of training my rust skills! ;D

**Comment by selaux** [comment]
I was thinking about replacing `FileMan` and `LibraryDataBase` with rust code as this would eliminate our dependency on boost. I've seen that you started to look at https://github.com/germangb/mini-fs, which I also stumbled over when looking for a virtual file system for the game. I'd suggest helping that project if you want to learn more about Generics and Traits in Rust.

**Pull request closed without merging**
