### PR TITLE
Fixed tactical world rendering when scrolling to top left

### PR DESCRIPTION
**Pull request by maxrd2**
This patch solves #119 
Please do not merge it yet.. I need to test it properly, and check it against other possibly related issues first.

### CODE REVIEW

**Comment by maxrd2** [comment]
Think it's all good for merging. Should i make separate PR for each commit or is it ok like this?
It should fix all frustrating issues referenced in #225

**Comment by selaux** [comment]
Thanks for the extensive PR :+1:. I think we can keep all this stuff in a single PR. I would like to do some testing of these changes myself, but I don't know when I will get around to do this though.

**Comment by selaux** [comment]
Allright I got around to a little testing and noticed some issues (tested the starting sector `A9` in `1280x720` resolution)

- The green radar rectangle changes size by probably one pixel when scrolling to the top of the map as well as when scrolling to the bottom
- When scrolling to the top-left of the map and scrolling up and down, the rendered tiles jump by one tile at some specific scroll position

I didn't test the individual issues yet, but I think those two issues should be fixed before more in-depth testing...

**Comment by maxrd2** [comment]
Scrolling the top left issue is what this patch intended to fix, and it fixed it for 1600x900 and other resolutions I've tried. It apparently broke it on 1280x720, will update it soon.

Green radar rectangle changing size is consequence of adding MIN() to rendering code so it doesn't cut the rect off. There are more tiles on tactical map shown than there are on the radar and rectangle is supposed to show exactly location on map. Will try to update the map drawing code to show pixels for all tiles that are shown on map if that's possible so this will get fixed.

**Comment by maxrd2** [comment]
Have re-fixed the issue #119 on some resolutions there was a problem with integer division/rounding.
Have tested it on 640x480, 1280x720, 1600x900, 1920x1080. Am pretty sure it will be fine on other resolutions too.

**Comment by maxrd2** [comment]
I can make separate pull request for the other issues. Top-left rendering problem is not actually related to radar map display and other 2 issues. That way should be easier to test it. Should I do that?

**Comment by selaux** [comment]
Yeah, sounds like a good idea.

**Comment by maxrd2** [comment]
Have managed to find another case (moving map way outside of the usable area to the north) where jumping was occurring and it was all due to bad integer division rounding. Am pretty sure #119 is solved for good with these.
Have retested it on 640x480, 1280x720, 1600x900, 1920x1080.

**Comment by maxrd2** [comment]
Have rebased to current master, and cleaned up coordinate conversion code in hope it will be more obvious.
Here's an attempt at explaining what was done here, and some extra info for future reference. Hope it will be easier to review and merge this now.

JA2 uses 3 types of coordinates: screen, world and map.
Screen coordinates are isometric projection of Map and World (cartesian) coordinates. World units (sometimes referred as cell units) are CELL_*_SIZE multiples of Map units.

file `src/game/TileEngine/WorldDef.h` contains defines CELL_*_SIZE and WORLD_TILE_*
```c++
#define CELL_X_SIZE             10 // worldX = 10 * mapX
#define CELL_Y_SIZE             10 // worldY = 10 * mapY
#define WORLD_TILE_X            40 // screenX = 40 * (map isometric)
#define WORLD_TILE_Y            20 // screenY = 20 * (map isometric)

#define HALF_TILE_WIDTH		((WORLD_TILE_X / CELL_X_SIZE) / 2)	// equals to 2
#define HALF_TILE_HEIGHT	((WORLD_TILE_Y / CELL_Y_SIZE) / 2)	// equals to 1
```

```c++
// world to screen conversion
screenX = (worldX - worldY) * HALF_TILE_WIDTH;
screenY = (worldX + worldY) * HALF_TILE_HEIGHT;

// screen to world conversion
worldX = (screenX / HALF_TILE_WIDTH + screenY / HALF_TILE_HEIGHT) / 2;
worldY = (screenY / HALF_TILE_HEIGHT - screenX / HALF_TILE_WIDTH) / 2;

// map to world(cell) conversion
worldX = mapX * CELL_X_SIZE;
worldY = mapY * CELL_Y_SIZE;
```

Sometimes world/screen coordinates are negative (in top left).
Old code used integer division so world of -25 when converted to map would be calculated as `-25 / 10 = -2.5`, integer casting would "round" that to `-2` instead of `-3` (which `floor(-2.5)` would do).
Conversion from isometric to cartesian involves formula of cartesian (x, y) to produce other isometric (x) and vice versa.
There were a bunch of (bugged) ifs() to detect these cases that would alter cart/iso(x, y) iso/cart x/y were negative, have changed everything to use floating point division. There are no more rounding errors which need to be worked around with code. There are no more unreadable/non-obvious if() conditions.

**Comment by lynxlynxlynx** [comment]
LGTM and thanks for the extra elaboration!

**Comment by maxrd2** [comment]
You're welcome. It took me awhile to wrap my head around all those coordinates and integer constants used in calculations, hope that will save time for anyone looking at it in the future.

**Comment by selaux** [comment]
:top: Tested a little and seems to work nicely. Thanks for investing some time here...

**Pull request merged**
