### PR TITLE
Change char* to ST::string

### PR DESCRIPTION
**Pull request by flaviojs**
This PR aims to convert most uses of `char*` with `ST::string` and fix string related issues.

Refactoring is not the aim, but will probably happen. I hope I don't change too much...

### CODE REVIEW

**Comment by flaviojs** [comment]
This PR will change DefaultContentManager a lot.
To avoid conflicts I'll postpone this for after #1011 (and similar) is done.

**Comment by ja2-derek** [comment]
There should be just one more PR for #1011, which is to parameterize several NPC interactions

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ja2-derek** [comment]
I am not expecting any need for further DefaultContentManager changes from #1011.

**Comment by flaviojs** [comment]
There are way too many changes, I'll split up changes to multiple PRs.
For now I'll leave this open.

**Comment by selaux** [comment]
Closing this, as it looks outdated (most of the things are already done).

**Pull request closed without merging**
