### PR TITLE
Fixed bug when picking up items during combat doesn't deduct APs

### LINKED ISSUE #763: Picking up item for 0 AP
### Picking up item from the ground takes 0 AP
Trivial to reproduce, seems to happen every time but I nevertheless attached a save.
In tactical mode, UI shows that picking up item from the ground takes 3 AP. But actually it takes 0.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  383211b | JA2 Gold En  |        |        |

[s.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2775503/s.zip)

### LINKED ISSUE #790: Picking up item from the ground for 0 AP
Pick up the gun at Johny's feet

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
| f970499 |  JA2 Gold En  |        |       |

[s.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2896700/s.zip)

### PR DESCRIPTION
**Pull request by agordeevw**
Should fix #790.
Also fix #763.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
LGTM. I thought it may be just a problem with the zero check in src/game/Tactical/Handle_UI.cc:3354, but that's only for item pools (groups).

**Comment by agordeevw** [comment]
Fixes #763 too.

**Comment by agordeevw** [comment]
Save provided with #790 allows to check three scenarios:
1. Player picks one item from ground (under Johny)
2. Player picks items from pool (on roof near Barry)
3. AI picks one item from ground (move Johny away from gun, enemy nearby stands up and picks up the gun)
In all cases soldier loses 3 AP after picking up, as expected.

**Comment by lynxlynxlynx** [comment]
Thank you very much!

**Pull request merged**
