### PR TITLE
Notify the player of important NPC in sector

### PR DESCRIPTION
**Pull request by ja2-derek**
Ported from Unfinished Business ([PATCH152](https://github.com/ja2-derek/ja2-ub-comparison/commit/7eb9ea13)). See also #1198.

If you travel to or going through a sector with an NPC (e.g. Skyrider), there is a prompt saying something like "Squad 1 noticed someone in sector A1". But if the sector has an enemy presence, then you will be going to battle instead, without any prompt about the NPC. This PR adds a prompt in tactical after winning a battle, that says "There is someone else in sector...".

This feature is more important in UB because there are always enemies in the sector where RPC `MANUEL` is.

## Changes

- Added new message string (English and [German](https://github.com/ja2-derek/ja2-ub-comparison/blob/master/src_common/game/Utils/_Ja25GermanText.c#L155) messages from UB source code)
- Adds an asynchronous check after winning a battle
    - We wait until all other things are done (e.g. win-battle quote, auto-bandaging) 
    - Shares the same check with the one in Strategic Movement (`WildernessSectorWithAllProfiledNPCsNotSpokenWith`)
- Differences from UB PATCH152:
    - UB implementation uses Game Event and persists into saves
    - This implementation uses a callback timer, so we do not need to modify events and saves
    - Notification is lost if player exits tactical immediately after battle

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks fine, thanks!

**Comment by ja2-derek** [comment]
Now the "There is someone else" dialogue pops up after killing all enemies in the first sector (because of Fatima). 

This is probably too big a deviation from Vanilla. I am thinking what to do about this..

**Comment by lynxlynxlynx** [comment]
Another field in the npc data json?

**Comment by ja2-derek** [comment]
My bad. There is actually no problem. I had just messed up the JSON data in my dev env.

The check uses `WildernessSectorWithAllProfiledNPCsNotSpokenWith`, and A9 Omerta is a town sector so the pop up will not be shown.

**Pull request merged**
