### PR TITLE
Fix issue with spaces in build path

### LINKED ISSUE #529: Build fails if there is a space in the directory name
@selaux: I just discovered this because Qt Creator's defaults folder name for a RelWithDebInfo build contains spaces.

The rust portion of the build process fails. 

```
[Manuel@K ja-stracciatella.git]$ mkdir "build with space"
[Manuel@K ja-stracciatella.git]$ cd build\ with\ space/
[Manuel@K build with space]$ cmake ..
-- The C compiler identification is GNU 7.1.1
-- The CXX compiler identification is GNU 7.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting extra data dir to
<FindSDL2.cmake>
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
</FindSDL2.cmake>
-- Found SDL2: /usr/lib/libSDL2main.a;/usr/lib/libSDL2.so;-lpthread  
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Compiling with local RapidJSON libraries from /home/Manuel/ja-stracciatella.git/dependencies/lib-rapidjson
-- Found Cargo: /usr/bin/cargo (found suitable version "0.18.0", minimum required is "0.9.0") 
-- Found Rustc: /usr/bin/rustc (found suitable version "1.17.0", minimum required is "1.15.0") 
-- Compiling with unittests
-- Compiling with local GTest libraries from /home/Manuel/ja-stracciatella.git/dependencies/lib-gtest
-- Found PythonInterp: /usr/bin/python (found version "3.6.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Manuel/ja-stracciatella.git/build with space
[Manuel@K build with space]$ make
Scanning dependencies of target gtest
[  0%] Building CXX object dependencies/lib-gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  0%] Linking CXX static library libgtest.a
[  0%] Built target gtest
Scanning dependencies of target slog
[  0%] Building C object src/slog/CMakeFiles/slog.dir/slog.c.o
[  0%] Linking C static library libslog.a
[  0%] Built target slog
Scanning dependencies of target rust-build
No such file or directory
make[2]: *** [rust/CMakeFiles/rust-build.dir/build.make:57: rust/CMakeFiles/rust-build] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:749: rust/CMakeFiles/rust-build.dir/all] Fehler 2
make: *** [Makefile:152: all] Fehler 2
```

### PR DESCRIPTION
**Pull request by selaux**
I dont have a lot of time currenly for this project, but hopefully enough to fix #529 🙂 .

### CODE REVIEW

**Comment by Manuel-K** [comment]
That change does look good and very straightforward. If it wasn't so warm, I would have tried to look at it, myself. ;-)

**Comment by Manuel-K** [comment]
You missed one. There is another `CARGO_TARGET_DIR=${NATIVE_BUILD_DIR}` on line 30.

**Comment by selaux** [comment]
If it wasnt so warm I would write better PRs 😉 , thx.

**Comment by Manuel-K** [comment]
That was not enough:

```
[ 99%] Building CXX object CMakeFiles/ja2.dir/src/sgp/UTF8String_unittest.cc.o
make[2]: *** Keine Regel vorhanden, um das Ziel „../build/ with/ space/rust/release/libstracciatella.so“, 
  benötigt von „ja2“, zu erstellen.  Schluss.
```

**Comment by Manuel-K** [comment]
The problem seems to be caused by the `IMPORTED_LOCATION` line…

**Comment by lynxlynxlynx** [comment]
Does quoting that fix it for you?

**Comment by Manuel-K** [comment]
No. Quoting does not change anything.
At the moment it uses `${NATIVE_LIBRARY_LOCATION}` which seems to be the reason for the `/\ ` inserted into the path instead of just `\ `. I tried to change it to `$"{LIBRARY_LOCATION}"`, but it seems to ignore the quotes.

**Comment by lynxlynxlynx** [comment]
$"{LIBRARY_LOCATION}" or "${LIBRARY_LOCATION}"?

**Comment by Manuel-K** [comment]
Second one. Stupid typo.

**Comment by selaux** [comment]
Closing in favor of #535

**Pull request closed without merging**
