### PR TITLE
WIP: Externalize translations

### PR DESCRIPTION
**Pull request by momoko-h**
Part 1: add code to export the translations to JSON.

Since this code is supposed to run exactly once to produce the JSON files before it is removed again this is just a quick and dirty implementation. Only Git will remember it ever existed...

I am somewhat concerned about the legal status of these translations. Aren't these strings copyrighted material that we aren't allowed to ship? Would be a shame to implement loading these files only to find out the work was all for naught.

### CODE REVIEW

**Comment by ja2-derek** [comment]
I am not a lawyer, but those strings were part of the original source code. So shouldn't they be under the same license?

**Comment by lynxlynxlynx** [comment]
I can't see an issue either.

**Comment by selaux** [comment]
I also think it's fine. Everything is still distributed under the same license.

**Comment by lynxlynxlynx** [comment]
Please also run a formatter on the json files, so translators will have an easier time editing and reviewing.

**Pull request merged**
