### PR TITLE
Better editor save load dialog

### LINKED ISSUE #667: slf archive and folder confusion
edit

EDIT:

the editor loads map files from maps.slf. when saving a map, the editor seems to check maps.slf for the existence of the specific map file. This generates the "map exists" warning. When saving, the new map file is saved to the folder, where nothing is overwritten, because the folder is empty.

### PR DESCRIPTION
**Pull request by selaux**
This is also part of #1275.

The main issue was that maps were always saved in the vanilla game directory. So for creating a mod you needed to always copy files back and forth between vanilla game dir and mods. At the same time listing all maps was broken, so no existing files were actually shown in the file list, leading to issues like #667.

For now I changed the editor load/save dialog to work on absolute paths. It is still possible to load a map from resources via the summary view in the editor, the save button in the summary view will now open the save dialog though.

- Navigation between folders is possible
- Start folder is the stracciatella home directory

Before:
Screenshot from 2021-05-03 09-03-44

After:
Screenshot from 2021-05-03 09-02-59

This also closes #667.

### CODE REVIEW

**Comment by selaux** [comment]
Found the issue that happened in the unit tests...

**Comment by lynxlynxlynx** [comment]
It's so self-contained I'm willing to just merge it. Do you want to take a look @ja2-derek ?

**Comment by ja2-derek** [comment]
It is a great improvement to the editor, and the code changes look good to me. Thank you @selaux!

**Comment by lynxlynxlynx** [comment]
Thank you both. :)

**Pull request merged**
