### PR TITLE
Fix msys2 issues

### LINKED ISSUE #590: failure when building on msys2
make
[  0%] Built target gtest
[  0%] Built target slog
warning: unused manifest key: package.release-debuginfo
       Fresh winapi-build v0.1.1
       Fresh itoa v0.1.1
       Fresh winapi v0.2.8
       Fresh num-traits v0.1.40
       Fresh dtoa v0.2.2
       Fresh libc v0.2.29
       Fresh serde v0.8.23
       Fresh getopts v0.2.14 (https://github.com/rust-lang-nursery/getopts?rev=b8beaf63#b8beaf63)
       Fresh serde_json v0.8.6
       Fresh shell32-sys v0.1.1
       Fresh user32-sys v0.2.0
       Fresh stracciatella v0.1.0 (file:///C:/msys64/home/askon/ja2-stracciatella/rust)
    Finished release [optimized] target(s) in 0.0 secs
[  0%] Built target rust-build
[  2%] Built target smacker
make[2]: *** No rule to make target 'rust/release/libstracciatella.dll.dll.a', needed by 'ja2.exe'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:135: CMakeFiles/ja2.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

[full_log.txt](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1253723/full_log.txt)

### PR DESCRIPTION
**Pull request by flaviojs**
Closes #590 

The x64_86 version works.
The i686 version works.

msys2 steps:
```
# install msys2 (https://www.msys2.org/)
# open "MSYS MinGW 64-bit" to build 64-bit or "MSYS MinGW 32-bit" to build 32-bit
pacman -Syu # update (might have to restart msys2 and run this again)
pacman -S base-devel
pacman -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-rust mingw-w64-x86_64-cmake mingw-w64-x86_64-SDL2 mingw-w64-x86_64-boost mingw-w64-x86_64-fltk # to build 64-bit
pacman -S mingw-w64-i686-toolchain mingw-w64-i686-rust mingw-w64-i686-cmake mingw-w64-i686-SDL2 mingw-w64-i686-boost mingw-w64-i686-fltk # to build 32-bit
# get ja2-stracciatella and cd into it
mkdir _bin && cd _bin
cmake .. "-GMSYS Makefiles" -DCPACK_GENERATOR=ZIP
make package
# extract zip, try ja2-launcher.exe and ja2.exe
```

### CODE REVIEW

**Comment by selaux** [comment]
I think if we want to support msys, we should also build it in our CI pipeline. Do you mind adding that to the PR?

**Comment by flaviojs** [comment]
I can do it in AppVeyor, but the generated zip has the same name as the cross compiled mingw build.

**Comment by flaviojs** [comment]
I'll try github actions first, since I found https://github.com/numworks/setup-msys2.

**Comment by flaviojs** [comment]
I have no idea what is the problem. Seems like a cargo problem, which I can't reproduce here...

**Comment by flaviojs** [comment]
Good, it can build in AppVeyor. Now I just need to figure out how to set it up properly and fix the tests.

**Comment by flaviojs** [comment]
Finally, a successful build after 31 commits.

Before I clean up the commits, the package name must be fixed.
Currently mingw always uses `win-mingw`.
What do you think about using `win-mingw32`/`win-mingw64` and adding `-cross`/`-msys2` based on how it's built?

**Comment by selaux** [comment]
Sounds good to me :+1:

**Pull request merged**
