### PR TITLE
Fix deb linting errors

### PR DESCRIPTION
**Pull request by selaux**

### CODE REVIEW

**Comment by selaux** [comment]
It is actually linting errors, warnings that are displayed when installing the package 🙂

**Comment by Manuel-K** [comment]
Oh, sorry. I only know linting from an IDE/separate linter.

But it thought it was about this linking related change  `OR CMAKE_BUILD_TYPE STREQUAL "Release"`.

**Comment by Manuel-K** [comment]
```
/Users/travis/.travis/job_stages: line 57: fakeroot: command not found

The command "fakeroot -v" failed and exited with 127 during .
```

**Comment by Manuel-K** [comment]
It seems to require a ` - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then`

**Comment by selaux** [comment]
The `OR CMAKE_BUILD_TYPE STREQUAL "Release"` is just something I noticed while implementing...

**Pull request merged**
