### PR TITLE
Add separate tab for mods to launcher

### LINKED ISSUE #1352: Launcher: preload all mods
Now it looks like only one mod is packaged, but actually all are available, one just has to click on Add first.

EDIT: hmm, that affects the save dir name, even if the mods are not enabled. Not sure if it matters.

### PR DESCRIPTION
**Pull request by selaux**
This should fix the confusion about enabled vs available mods in the launcher. It adds a new mod tab to the launcher that shows clearly which mods are available and which are enabled in two separate lists. Mods can then be enabled/disabled by moving them between lists using the buttons in the middle.

Closes #1352

Screenshot from 2021-10-17 15-06-28

I needed to increase the launcher size a little in order to fit all mod names. For longer mod names it will show a horizontal scroll bar. There is some behavior implemented to lead the user to correctly use the interface (e.g. buttons are enabled/disabled depending on which list is selected)

I intentionally left some space below the mods to be able to display mod information (e.g. from a mod manifest) later.

### CODE REVIEW

**Comment by ja2-derek** [comment]
I like the new tab. It is much more intuitive, to me.

But I wonder if `mods-available` and `mods-enabled` are clear enough for people who never did Linux admin before. Maybe we can say something like "mods disabled" instead; or, is it easy to add mouse-over tooltip?

**Comment by selaux** [comment]
I adapted the naming to Enabled/Disabled mods. I also tried to add some explanation for priority to the tooltips of the respective buttons.

Regarding the "Data" tab I would leave it as is right now. I think there might be new content coming in the future there (e.g. #1337).

**Comment by ja2-derek** [comment]
@lynxlynxlynx, do you know if the build failure is a problem with AppImageLint, or something to be changed in build config?

```
  File "/tmp/.mount_appimas4L9EQ/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 131, in _check_ubuntu_compat
    max_supported_version = versions_map[release]
KeyError: 'impish'
```

**Comment by lynxlynxlynx** [comment]
Pretty sure it's the same cache issue it had before. We were discussing it upstream, but since it went away on its own back then, perhaps nothing was done to mitigate in the future, even though it was discussed. 
https://github.com/TheAssassin/appimagelint/issues/22

**Pull request merged**
