### PR TITLE
Fix and enhance cli switch parsing

### PR DESCRIPTION
**Pull request by selaux**
Fixes:
- JSON options being prefered over cli switches

Adds:
- Datadir cli switch to set vanilla data directory

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
LGTM, but I can't test yet (will return in a week).

**Comment by Manuel-K** [comment]
I've messed up the path in ja2.json and was able to override it with -datadir using an absolute path. Relative paths do not work.

**Comment by selaux** [comment]
@Manuel-K Nice catch! I will try to add relative path support to the PR as it definitely makes sense.

**Comment by Manuel-K** [comment]
Can we merge this and leave the support of relative paths for later?

**Comment by lynxlynxlynx** [comment]
Sure, merge and open an issue for the rest, so it's not forgotten.

**Comment by Manuel-K** [comment]
Okay. That wasn't a good idea.

Is seems to have caused a lot of CI issues, although the x64 platform on AppVeyor seems to be broken for everything at the moment. 

Travis reports a problem on Mac:
```
thread 'tests::parse_json_config_should_return_the_correct_canonical_data_dir_on_linux' panicked at 'assertion failed: `(left == right)` (left: `"/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/ja2-tests.7FhrfeFjMhqO"`, right: `"/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/ja2-tests.7FhrfeFjMhqO"`)', src/stracciatella.rs:650
```

**Comment by Manuel-K** [comment]
Should I disable the test on Mac by changing the `#[cfg(not(windows))]` to `#[cfg(linux)]`?

**Comment by Manuel-K** [comment]
Okay. It seems that the corresponding test on Windows fails as well.

**Comment by Manuel-K** [comment]
@lynxlynxlynx I'm in favour of reverting this for now.

**Comment by lynxlynxlynx** [comment]
The only difference in the paths is that left has /private prepended. Maybe a travis thing we're not accounting for, since this is a new test?

**Comment by selaux** [comment]
That is why I didn't proceed right away, especially on windows this results in weird directories...

**Comment by lynxlynxlynx** [comment]
Couldn't find any references to /private, but it's also impossible to search for. I guess it would be easiest to stick a bunch of prints in the test locally, as it appears it's actually the temp dir creation module where the problems start.

**Comment by Manuel-K** [comment]
Similar issue on Windows:
```
 thread 'tests::parse_json_config_should_return_the_correct_canonical_data_dir_on_windows' panicked at 'assertion failed: `(left == right)` (left: `"\\\\?\\C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\ja2-tests.P2CY6hCvnVJT"`, right: `"C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\ja2-tests.P2CY6hCvnVJT"`)', src/stracciatella.rs:667
```
It adds `"\\\\?\\`.

Anyhow: Reverting the last commit seems to be the way to go. I've pushed a branch that does that. Let's see if the CI still complains.

**Comment by selaux** [comment]
Relevant Rust issue for Windows: https://github.com/rust-lang/rust/issues/42869. So as I read this it might be ok to simply remove this prefix...

For macOS my guess is that this is a resolved symlink (as this is also done by canonicalize and the path looks almost correct).

**Comment by Manuel-K** [comment]
It looks that way. This means that with the current code only the test fails on Mac while relative paths are completely broken on Windows.

**Comment by selaux** [comment]
Well for Windows paths we need to strip the prefix (they might even work with them, we could check that) and for macOS only the tests are broken.

**Pull request merged**
