### PR TITLE
Fix AI hang during turn based combat

### LINKED ISSUE #466: AI deadlocks
Version 409ae2a2. Throughout my game, every battle has been slowed down by multiple AI deadlocks per turn. Example attached; end the turn, and you should get several AI deadlocks:

[SaveGame07.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/662343/SaveGame07.sav.zip)

2016/11/19 19:55:46 ERROR   [AI              ] Aborting AI deadlock for 26. Please sent LOG file and SAVE.
2016/11/19 19:56:10 ERROR   [AI              ] Aborting AI deadlock for 34. Please sent LOG file and SAVE.
2016/11/19 19:56:28 ERROR   [AI              ] Aborting AI deadlock for 36. Please sent LOG file and SAVE.

### PR DESCRIPTION
**Pull request by momoko-h**
The AI actions CHANGE_FACING and CHANGE_STANCE must be included in the
movement actions otherwise the soldiers can never reach their target. Closes #466

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks, sounds sensible. How much testing/theorizing did you do?

**Comment by momoko-h** [comment]
I started with selaux' observation that it only happened when pSoldier->bAction is  AI_ACTION_CHANGE_STANCE, so I watched for that and then quickly noticed that the code at AIMain.cc line 418 where the comment says "an old action was in progress; continue it" was reached again and again without actually doing anything because it immediately failed the if check in line 419.

Testing: I observed the hang happening with Reaper against a single soldier in Omerta and verified that the patch fixes the hang. Then I played a couple of minutes with a 5 mercs against 6 soldiers situation and didn't notice any problems.

**Comment by lynxlynxlynx** [comment]
Perfect, thanks again!

**Comment by RinneT** [comment]
Really awesome you could fix it. Thanks so much!

**Comment by andreas12345** [comment]
Awesome, thanks a lot!

**Comment by chmallon** [comment]
Did you consider the implications of this change on MovementMode[][]?
(which already misses one initializer for vanilla)

**Comment by Manuel-K** [comment]
Interesting. `AI_ACTION_MOVE_TO_CLIMB`, `AI_ACTION_CHANGE_FACING` and `AI_ACTION_CHANGE_STANCE` are uninitialized. `{WALKING,  WALKING,  WALKING}` or `{WALKING,  RUNNING,  RUNNING}` seem to be the most obvious choices.

**Comment by Manuel-K** [comment]
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/game/TacticalAI/AIUtils.cc#L42

**Comment by chmallon** [comment]
It's a global array, so it is zero-intialized, i.e. in this case WALKING.

**Comment by Manuel-K** [comment]
That is not an answer to the question what the values should be, but you obviously know that.

**Comment by lynxlynxlynx** [comment]
While it doesn't seem to matter much (most code treats both walking and running equally), I agree that {WALKING, RUNNING, RUNNING } looks like a good choice for the missing two.

**Pull request merged**
