### PR TITLE
Only dont show tactical messages if time is being compressed

### LINKED ISSUE #398: Experience gain not acknowledged properly
The squad found Skyrider. When Hitman talks to him, the squad gains EXP and Barry goes up a level. He gives his comment as expected.
However, the game does not acknowledge it in the lower left corner, like it does usually ("Barry gains 1 level of experience").
barry1

The gained level is still normally visible in Barry's inventory screen:
barry2

So, only the text doesn't appear.

Savegame:
[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/501338/QuickSave.zip)

### PR DESCRIPTION
**Pull request by selaux**
@JAsmine-ja2 Can you test if that fixes #398 properly?

Builds: http://builds-ja2.stefanlau.com/pull-requests/465/

### CODE REVIEW

**Comment by JAsmine-ja2** [comment]
error

I can't open the windows build (32 and 64 bit)

**Comment by selaux** [comment]
@JAsmine-ja2 Did you adapt your `ja2.json` which replaces `ja2.ini`? You need to put your data dir in there (with double backslashes).

The error message should be better though...

**Comment by JAsmine-ja2** [comment]
Okay, I've played around with this a bit. So far, it _seems_ to work. Can't tell for 100% sure, since I don't have a savegame with the issue (#160) at hand. It happened on a seemingly random basis.
Anyway, great job (as usual) and for the time being, I think we can close #160.

**Comment by lynxlynxlynx** [comment]
This PR doesn't affect #160, some previous did. Did you mean #398?

**Comment by JAsmine-ja2** [comment]
Sorry, my bad. Seemingly, I was a bit confused last night. Ofc, I meant #398. Everything else I wrote applies, though.

**Comment by lynxlynxlynx** [comment]
The backslash thing is the way escaping works. Please open a new report if we don't error out nicely on invalid game paths (that's how it resolves).

**Pull request merged**
