### PR TITLE
Replace LibraryDB with Vfs

### PR DESCRIPTION
**Pull request by flaviojs**
~v1: Rework LibraryDB~
v2: Replace LibraryDB with Vfs

Supports filesystem directories and slf archives.
Can be expanded to support other archive types.

Vfs and VfsFile are independent but not thread-safe.
Make sure each object is only used by one thread at a time.

### CODE REVIEW

**Comment by flaviojs** [comment]
I'm considering expanding LibraryDB to also handle data dirs. But that means it's a virtual file system.
If this is a virtual filesystem, maybe it should also handle writable paths like the current directory, TMPDIR and DEVINFO_DIR.

I can't decide if I should go with this... give me your thoughts.

**Comment by ja2-derek** [comment]
I wish that .SLF can be used in mod directories.

It seems opening a large number of small files (at least on Windows) is pretty slow. Having a mod of thousands of resources (mostly tileset and tilecaches) makes the game slow. File caching kicks in eventually, but the first load can be quite slow. I am talking about ~10s freeze when loading a map. This is very slow, for a 20 years old game running on a modern PC.

**Comment by lynxlynxlynx** [comment]
I don't know how things are currently organized or what the impact would be, so ¯\_(ツ)_/¯.

**Comment by flaviojs** [comment]
Allowing slfs in mod dirs should be easy. ;)

As for the current structure, #707 contains my old findings about how things are organized (excluding TMPDIR and DEVINFO_DIR).

Readable dirs are easy, the logic is similar to the current handling of slfs (filenames are case insensitive and shadowed).

Writable dirs are tricky, shadowing might not be appropriate.
What should happen if I delete a file in a writable dir and it was shadowing another file? I can't decide.

I'll try implementing readable data dirs and skip writable dirs for now...

**Comment by flaviojs** [comment]
I ended up reimplementing LibraryDB as a virtual file system Vfs.

The ordering is based on my old proposal (https://github.com/ja2-stracciatella/ja2-stracciatella/issues/707#issuecomment-509862638) with a few changes:
 * the current dir is not handled by Vfs, it gave me problems that I didn't understand
 * the free editor.slf at the end (fallback)

For now it is read-only.

**Comment by flaviojs** [comment]
Hmm, going for writable dirs seems like a bad idea for now.

As a final note, this PR changed the order of the "current dir".
Before it came after mods and externalized.
Now it comes first.

**Comment by lynxlynxlynx** [comment]
Is "current dir" still our tmp dir, not whatever CWD ja2 was ran from?

**Comment by flaviojs** [comment]
Yup, the current dir is set to out tmp dir in `FileMan::switchTmpFolder`.

**Comment by flaviojs** [comment]
Hmm, I'm tempted to just go ahead and merge so I can continue my other PR...

**Comment by lynxlynxlynx** [comment]
Yeah, let's go ahead. Things are finally congealing for a nicely cut 0.17 release.

**Comment by selaux** [comment]
Yeah, sorry currently I am not able to review stuff, quickly...

**Pull request merged**
