### PR TITLE
Add Appveyor CI

### PR DESCRIPTION
**Pull request by selaux**
Readding the BOM's was required for the unittests to work. Building on Openbsd is broken afterwards for me though, which is fixed in #441.

Additionally I created a bot user and shared email account for the stracciatella team. Bot should be used to e.g. automatically attach links to builds to pull requests. The shared email is used for the bot user. We should exchange credentials somehow.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks ok. I can't find the project though — can you share a link?

**Comment by selaux** [comment]
https://ci.appveyor.com/project/madlab-bot/ja2-stracciatella, it's also linked in the "Successful Checks" section below.

**Comment by lynxlynxlynx** [comment]
hmm, there doesn't seem to be a way for me to add it to my list.

**Comment by selaux** [comment]
I added you to the team as an Admin. Others have to sign up before to get access @derSteFfi

**Comment by lynxlynxlynx** [comment]
Odd, still not visible under Projects.

**Comment by selaux** [comment]
But do you have access now?

**Comment by lynxlynxlynx** [comment]
Same as before, I can check the status and logs, but that's it. No settings or restarting buids. Did you add as a "github team"?

**Comment by selaux** [comment]
No, I don't really understand how the github team thing works (it didn't show anything when I tried to add one). Can you maybe try to create a new project and invite the rest?

**Comment by lynxlynxlynx** [comment]
The way I see it, it should grant the team access to the madlab appveyor account, so you'd have to be logged in as that for it to make sense. For kicks, I tried to add you as an appveyor collaborator to my account, but it didn't find your email.

**Comment by lynxlynxlynx** [comment]
Eh, it's simple. You have to log out and log in again. Then you'll be presented with which account to use.

**Pull request merged**
