### PR TITLE
Build VS2017 on appveyor

### PR DESCRIPTION
**Pull request by selaux**
Updates gtest to most recent version.

Makes CI builds quite long unfortunately. Maybe we should decide for one version.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks nice, but I agree, there's no need for so many windows builds. I vote for the latest toolchain on 64-bit.

**Comment by lynxlynxlynx** [comment]
I think it's enough to do 32-bit builds only at release time.

**Comment by lynxlynxlynx** [comment]
One last thing: if we still allow for local gtest, why remove it? Did you forget to readd the updated version?

**Comment by selaux** [comment]
It is now dowloaded during the build, just like FLTK (see `dependencies/lib-gtest/CMakeLists.txt)`

**Comment by selaux** [comment]
This way we hopefully end up here at some point: https://github.com/ja2-stracciatella/ja2-stracciatella/pull/711. Just in smaller incements.

**Comment by lynxlynxlynx** [comment]
Ah, great!

**Pull request merged**
