### PR TITLE
ApplyScrolling: buffer the top border, so npcs there can be shot in t…

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
…he head #195

roof level automatically offsets, so such cases don't need to be handled separately

### CODE REVIEW

**Comment by selaux** [comment]
This offset seems a little high to me and causes some corruptions (e.g. suddenly ending fences). Shouldn't a lower value suffice?

**Comment by lynxlynxlynx** [comment]
Which sector are you looking at? I can see tree trunks get drawn on top of canopies in Meduna, but I don't have any saves with mercs in sectors with border fences. Since we need to draw a full extra grid row, I don't think we can change much here. The minimum value needed is 62.

**Comment by selaux** [comment]
Looking at I13: Alma:

screenshot from 2016-04-02 17-20-18

**Comment by lynxlynxlynx** [comment]
Ok, so it's not corruption, just level design issues. Looks better with the minimum though, so I'll push that.

**Comment by selaux** [comment]
Looks better now, butI can still see the broken level design. My suggestion would be to merge and revisit these issues after the release. 

Question: Why do we need to use a minimum value here?

**Comment by lynxlynxlynx** [comment]
We don't, but the minimum value minimizes the potential to see broken data, since less of it is exposed.

**Comment by derSteFfi** [comment]
looks good to me too.

**Comment by LonCJ** [comment]
Thought I'd mention there's also going to be a few places where you can see NPC that follows a schedule, like shopkeepers, before they become active.  You can't talk to them but they're still visible.   Suppose I should see if they can be attacked. 

For example Keith waiting for the pawn shop to open.
npc_waiting

**Comment by derSteFfi** [comment]
hm. yes, we should investigate this. I'd still say it's data bug (or a hack in the original to place npcs on not visible tiles) but this is more serious than a fence that ends or similiar stuff.

**Comment by lynxlynxlynx** [comment]
The original has the headshot bug, so it's immune. We could make NPCs outside the bbox invisible — we just did the reverse recently by showing anyone on inaccessible tiles.

**Comment by LonCJ** [comment]
Looks like they can be killed or something happens anyway.  Sprayed Keith with bullets for awhile and there's no indication of hits, as in blood or damage text, but after awhile he stuck in what looks a death animation frame.  Nothing showed in history log(if Keith even has a death entry) but he never reappeared in the store and just stayed in the same location in this pose.
keith

**Comment by selaux** [comment]
@LonCJ Can you provide a savegame for this, I'm to lazy to play til cambria :wink:

**Comment by selaux** [comment]
@lynxlynxlynx Any idea on how to fix this? There are two things I would like to check:

- Does #282 allow NPCs to move out of this area
- Is it possible to hide them (and are they invincible when hidden)

I tried finding the place where it sais that enemy soldiers outside the visible tiles dont render but I could not...

**Comment by LonCJ** [comment]
Sorry for the delay selaux don't know if you still need it.  Two savegames in zip, think the low number is Keith alive and high number is most likely dead Keith.

[Inactive_NPC_killable.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/296620/Inactive_NPC_killable.zip)

**Pull request merged**
