### PR TITLE
Fix #253 by eventually invalidating gpBattleGroup in RemoveGroup

### LINKED ISSUE #253: Crash after AI vs AI battles.
Getting a random crash after AI vs. AI battles.  Not sector specific and occurs maybe once every 10-20 battles.  Crashes cleanly to desktop without anything being logged or error.sav created.  So far unable to reproduce from savegame.  Last entry in log is always the radarmap for the sector the battle is occuring in. 

Battle resolves without issue.  After clicking the 'Done' button the screen goes completely black for a split second and then crashes to desktop.  Sorry I can't be any more vague.

### PR DESCRIPTION
**Pull request by derSteFfi**
This is more of a workaround, but it removes SEGFAULTs so I think it's worth it.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks good. You can now also remove the same code at:
Build/Strategic/Auto_Resolve.cc:400

**Comment by derSteFfi** [comment]
Yes, we could. Question is, can we eliminate one of two functions that call RemoveGroup at all? Anyway, invalidating gpBattleGroup will never ever take place where you pointed it out and thus can be removed.

**Comment by lynxlynxlynx** [comment]
I don't follow, one of two? I see many more callers.

**Comment by derSteFfi** [comment]
I meant the two conccurring i mentioned in the corresponding issue

**Comment by derSteFfi** [comment]
So, I added another check and logging. We should keep an eye on this, but I think this is the best we can do for now.

**Comment by LonCJ** [comment]
Thanks for this fix.  It's working perfectly for me.

**Pull request merged**
