### PR TITLE
Build AppImage for linux

### LINKED ISSUE #138: Create packages for Linux
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

It would be great to create packages for popular Linux distributions, so Linux users don't have to compile the game.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/138

### LINKED ISSUE #1213: Proposal: Build distro-agnostic packages for Linux releases instead of Debian Package
### What is wrong

Currently we only build a debian package for linux releases. This has the disadvantage that users of non debian-based systems have to compile the source for themselves, making the barrier to actually try out the game higher than necessary (e.g. I run arch linux, so i cannot test the PR builds as easily as I want to). Additionally it is not entirely clear with which debian-based system the deb package is actually compatible, although I personally never experienced issues with that.

### Proposal

We should have a look at more modern packaging options such as

- Flatpak
- AppImage
- Snap

I think the easiest route for us to go down is building AppImages, as there is no additional software required to run an AppImage on any Linux distribution, which makes the installation process quite easy (or even give the user the option not to install anything). Also we can keep the existing way of distributing releases via the github releases page. A disadvantage might be that we'll actually need some small code changes to support the game running from the AppImage. Also the adoption of AppImage is less than Snaps or Flatpaks respecitvely. What do you think?

PS: Here is a good comparison of the three (although it might be a little biased): https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison

### PR DESCRIPTION
**Pull request by selaux**
Some changes to currrent logic were necessary:

- Always search EXTRA_DATA_DIR relative to binary (makes binary relocatable)
- Install linuxdeploy in CI, to build the AppImage
- Add cmake task `package-appimage` that is executed instead of `package` for linux

Closes #1213. Closes #138.

I will wait for build and test the resulting AppImage on multiple distros before merging.

### CODE REVIEW

**Comment by ja2-derek** [comment]
EXTRA_DATA_DIR defaults to the executable directory. Is it simpler just to package data files under `./externalized` and skip EXTRA_DATA_DIR totally? Windows package already does that.

**Comment by selaux** [comment]
I think it is working now (lets see how Travis handles the master build). I tested the AppImage on:

- Fedora 32
- Ubuntu 20.04
- Debian 10
- Manjaro

Regarding removing EXTERNAL_DATA_DIR: I'd still like for the usual `make install` under Linux/BSD to work nicely. So as far as I can see this is still necessary.

**Comment by ja2-derek** [comment]
It complains of missing `editor.slf` when I try to start the editor. And can I start ja2 directly skipping the launcher?

**Comment by selaux** [comment]
I think the editor slf is not included with Pull Request builds as they are debug builds.

Currently it is not possible to start ja2 directly, we would need to write a wrapper script around `ja2` and `ja2-launcher` in order to do that.

**Comment by ja2-derek** [comment]
> I think the editor slf is not included with Pull Request builds as they are debug builds.


Ah right. So that's not a problem.

> Currently it is not possible to start ja2 directly, we would need to write a wrapper script around `ja2` and `ja2-launcher` in order to do that.

Not really a problem either. It's just one click on the JA2 Launcher.

**Comment by ja2-derek** [comment]
Travis build is failing:

https://travis-ci.org/github/ja2-stracciatella/ja2-stracciatella/jobs/727108794. Logs:
```
 if [ "$TRAVIS_MINGW" != "true" ]; then if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./AppDir/usr/bin/ja2 -unittests && ./AppDir/usr/bin/ja2-launcher -help; else ./ja2 -unittests && ./ja2-launcher -help; fi fi

/home/travis/.travis/functions: line 109: ./AppDir/usr/bin/ja2: No such file or directory

The command "if [ "$TRAVIS_MINGW" != "true" ]; then if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./AppDir/usr/bin/ja2 -unittests && ./AppDir/usr/bin/ja2-launcher -help; else ./ja2 -unittests && ./ja2-launcher -help; fi fi" exited with 127.
```

**Comment by selaux** [comment]
I will have a look later...

**Pull request merged**
