### PR TITLE
[RFC] Implementation of #360 (Folder renames)

### PR DESCRIPTION
**Pull request by Manuel-K**
This shows the source tree structure as suggested by @derSteFfi and without the samples subfolder of lib-slog.

I've probably missed something in CMakeLists.txt – I only tested building/linking/running on Linux.

### CODE REVIEW

**Comment by Manuel-K** [comment]
Hm. AppVeyor complains about SDL2…

**Comment by selaux** [comment]
Yes you have to adapte the toolchain files inside the cmake directory.

**Comment by selaux** [comment]
Imho we could merge, you just have to fix the conflicts...

**Comment by Manuel-K** [comment]
Self-created merge conflicts. That was very smart. ;-)

Rebased on master.

**Pull request merged**
