### PR TITLE
 Build release tags

### PR DESCRIPTION
**Pull request by selaux**
__Goal__: Build release packages when a git tag is created.

Also include some rust changes for the newest serde version that was released recently.

Contains a bunch of changes to CI, so I have to open a PR early again to ensure everything still works.

### CODE REVIEW

**Comment by selaux** [comment]
Should be working now. Test release is available here: http://builds-ja2.stefanlau.com/releases/

**Comment by selaux** [comment]
We get some warnings when installing the deb though (ownership of files etc.). Will fix in another PR.

**Comment by lynxlynxlynx** [comment]
Not that important, but the nigthlies should use the Debug BUILD_TYPE.

**Comment by selaux** [comment]
True, I tried adapting configuration per build, but I figured it is unachievable with appveyor. This is why I settled with using `RelWithDebInfo` everywhere. The only disadvantage is assertions being disabled for nightlies.

**Comment by Manuel-K** [comment]
I usually use `RelWithDebInfo` for testing. Too many weird bugs are caused by a higher optimization level which makes the `Debug` builds less useful.

**Comment by Manuel-K** [comment]
Should the release builds contain the data used by the unit tests?

**Comment by selaux** [comment]
They are built with unittest capabilities, so they also include the data. Not sure if it is worth to remove. Building with debug info also considerably increases the size of the releases.

**Comment by selaux** [comment]
Feel free to have a try at building releases with different build types. After spending a lot of time waiting for the CI and searching the web I just thought it isnt worth investigating further...

**Comment by selaux** [comment]
There is one more thing I will try...

So do we want to roughly double the release sizes by including debug info?

**Comment by Manuel-K** [comment]
No

**Comment by selaux** [comment]
Allright new releases have been built. Setting `BUILD_TYPE` now works nicely as well. Can be merged imho.

**Pull request merged**
