### PR TITLE
Use /MD runtime with MSVC

### LINKED ISSUE #641: Releases link against debug and release runtime on MSVC
Basically we need to redistribute debug and release dlls with MSVC releases. I am not sure why exactly.

I dont consider this a critical as it does not increase release size that much, it just clutters the directory.

### PR DESCRIPTION
**Pull request by flaviojs**
Fixes #641

### CODE REVIEW

**Comment by flaviojs** [comment]
Note that the debug dlls are still included in the zip/installer.
I haven't removed `CMAKE_INSTALL_DEBUG_LIBRARIES` because it also affects mingw and I don't know if it's needed.

**Comment by selaux** [comment]
I would remove it. According to [Documentation](https://cmake.org/cmake/help/v3.4/module/InstallRequiredSystemLibraries.html) is is only used for MSVC.

**Comment by flaviojs** [comment]
Nice, done.

**Comment by flaviojs** [comment]
So, can this be merged?

**Comment by lynxlynxlynx** [comment]
Thanks!

**Pull request merged**
