### PR TITLE
Cheat: alt+o damages bloodcats now

### PR DESCRIPTION
**Pull request by daviel**
fixes the second part of #126

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
The core bit looks fine, but the damage looks too low — can it still affect tanks? See where all this started: #503

**Comment by daviel** [comment]
Works totally fine with tanks. Took the gamesaves out of #503. You will need to press alt+o up to 4 times though.

**Comment by lynxlynxlynx** [comment]
So the damage should be higher. If it's causing healing somehow, that's a separate bug that should be fixed as well at some point.

**Comment by daviel** [comment]
Okay, so it seems that in the code there is a 2-times multiplier for the damage value. This could lead to an overflow on a 16-bit value. This could be reason for the false calculations for the maximum number of 0xFFFF. 
I thought of two solutions for this:
1. We set the damage value to a number we know is the highest health-value in game(queen-bug as far as I know)
2. We set the damage value to 0xFFFF divided by 2
What would you recommend?

**Comment by lynxlynxlynx** [comment]
I'd just set it to 10000, which is safe and much higher + a comment noting it should be high enough to kill tanks/queen and lower than 0xffff/2.

**Comment by daviel** [comment]
Okay, done.

**Comment by lynxlynxlynx** [comment]
Good enough, thanks!

**Pull request merged**
