### PR TITLE
Implement command line parsing in rust

### PR DESCRIPTION
**Pull request by selaux**
So here comes the rust prototype, regarding #355. Notes:
- The library implements a `CommandLineArgs` struct in rust ad exports utility functions to create it and get to its contents.
- Command line args currently need to be used with two dashes, e.g. `--fullscreen`

Discovered Pros:
- Code looks more understandable
- Tests are easy to write
- Dependencies can be loaded very easily
- Can be linked statically

Discovered Cons:
- Only simple structs may be used in rust as well as C++
- Memory management might be tedious sometimes, e.g. passing strings from rust to C++
- Kind of a weird interface

Builds 🙂 : http://builds-ja2.stefanlau.com/pull-requests/420/

### CODE REVIEW

**Comment by RinneT** [comment]
Very nice to see this takeoff, very good place to start as well.

My main downside so far is that I have to compile rust myself on my distro and it took literally two hours, far longer than any other package.

Works nicely, though.
What I don't understand is where the actual link to rust is in sgp.cc.
I see there are some calls, however how does the application know in which files to look for them?

**Comment by lynxlynxlynx** [comment]
From what I saw it's done during link time, so it's kind of a library interface.

**Comment by selaux** [comment]
Yes, it simply looks for the according symbols in the built static rust library. It's the `external` definitions.

**Comment by selaux** [comment]
So do you think we should go further into this direction? Then I might make the PR somehow bigger to encompass the `ja2.json` changes...

**Comment by lynxlynxlynx** [comment]
How easy is to set up rust on windows? Personally I don't care much either way, but it'd be a shame if we created a barrier for contribution.

Re --: args could be fixed before parsing, so we maintain backward compatibility. Either with a regex crate or manually.

**Comment by selaux** [comment]
Some more progress here. `ja2.json` parsing is implemented in rust now, including setting command line options with it. The MicroIni dependency has been removed. One drawback is that the rust serialization library does not support comments in json though. But I could also remove the MicroIni dependency this way.

Command line compatibility is fixed, we now use the current master of the `getops` crate which supports this. Stuff to optimize

- Tests for home dir creation and better error handling
- Having a better and safer interface to get rust strings in c++
- Testing `create_engine_options`

@RinneT You could probably also use http://rustup.rs/ to install the current rust version in your home dir.

**Comment by lynxlynxlynx** [comment]
Is it lacking only serialisation or also deserialisation support for comments?

Also you mistyped something about Microini.

**Comment by selaux** [comment]
Both currently. Not sure if they are wanting to implement that because it's not part of the spec. I will inquire about it.

Yes, it was already late in the evening 😉 . But MicroInI has been removed.

**Comment by selaux** [comment]
From my side this is now done. Two differences to before remain:

- CLI switches can now be used with double dashes as well as singe so `--fullscreen` works as well as `-fullscreen`
- No comments in ja2.json allowed

Featureset:
- Command line switches are evaluated in rust
- Finding home dir is done in rust
- ja2.json is evaluted in rust (and created if necessary)
- ja2.json allows for CLI switches to be specified, e.g. `{ ... "res": "1024x768" ... }`

All releases work for me (some fixups were needed for the nightly/debug builds anyways). Only "initial" dependency is rust and cargo that can be installed via [rustup]() on most systems. Rust dependencies will be pulled on demand.

**Comment by lynxlynxlynx** [comment]
For -options, I'd just document only the normal --options instead. It's good that the old ones work, but they're not standard, so I'd discourage them.

Comments we don't use yet, but it's a shame. Can we use placeholder fields for it instead?

The string cleanup makes everything look less scary.

**Comment by selaux** [comment]
I added a comment into the default json. Unfortunately it's not possible to document the `--` options with the argument parser library. We might remove the `-` ones when we include the launcher though, that will fix it.

**Comment by selaux** [comment]
So what about renaming `~/.ja2` to `~/.ja2-stracciatella`? Should we do it? And should we put in some migration logic so the user does not have to do it manually (we could do the same for the ini)?

**Comment by lynxlynxlynx** [comment]
I see no benefit. Also, what was the reason behing removing the shorthand options?

**Comment by selaux** [comment]
That they weren't there before. Imho there is not a lot of benefit in having them...

**Comment by selaux** [comment]
BTW: You see no benefit in changing or in adding migration? Because imho we could also leave the directory as it is and close the  ticket 🙂

**Comment by lynxlynxlynx** [comment]
No benefit in renaming.

**Pull request merged**
