### PR TITLE
Limit ci building to master branch

### PR DESCRIPTION
**Pull request by Manuel-K**
Let's hope that this does not block PR building.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
excellent :+1:

**Comment by lynxlynxlynx** [comment]
Hmpf, it was ok on this one, but #675 is building 4 again.

**Comment by Manuel-K** [comment]
Your branch does contain the old config files.  I've only checked the Travis documentation, but that states that the config from the current branch is used.

I assume if you were to rebase on master you would only get two PR builds.

**Comment by lynxlynxlynx** [comment]
right, doh, forgot to rebase first.

**Pull request merged**
