### PR TITLE
coverity: properly pass a cmake define [ci skip]

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
Grrr, now I really feel silly.

### CODE REVIEW

**Comment by momoko-h** [comment]
Why does that make a difference, we're just testing #ifdef ENABLE_ASSERTS, right?

**Comment by lynxlynxlynx** [comment]
CMake is being pedantic about its own syntax. What I wrote would work on the compiler command-line, but cmake itself wants a specific value. But this won't be enough either, come to think of it.

**Comment by momoko-h** [comment]
Ah OK. I've just read in the [CMake documentation](https://cmake.org/cmake/help/latest/command/add_definitions.html) that add_definitions has been superseded by add_compile_definitions since v3.12. Do we have a minimum supported CMake version older than that?

**Comment by lynxlynxlynx** [comment]
Currently: `cmake_minimum_required (VERSION 3.4)`

**Comment by momoko-h** [comment]
3.4 was released in 2015, and 3.12 in July 2018. GitHub's Ubuntu 18.04 has 3.23.2, so maybe it's time to raise that limit?

**Comment by lynxlynxlynx** [comment]
Do we gain anything? CMake is good about backward compatibility.

**Comment by lynxlynxlynx** [comment]
I don't know if it'd be useful, unless someone wanted to refactor our current android build. But I'm not against a bump, just was curious if it had any tangible benefits.

**Comment by momoko-h** [comment]
According to [this](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html), we would already need at least 3.8 for our current use of C++17 and if you want C++20 you'd need 3.12.

**Comment by selaux** [comment]
I would be fine with updating it to a more recent version (maybe at least 3.8 for proper compatibiltiy with C++17). We even have [a file](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/e23678b74af7e7fa2ccaf067eb44993184af0a33/dependencies/lib-smacker/CMakeLists.txt) which gives warnings about the required version (2.8) being too low and compatibility being removed. But it should probably not be part of this PR.

**Comment by momoko-h** [comment]
That did it! 25 of the 27 newly eliminated issues are due to this change.

**Comment by lynxlynxlynx** [comment]
Yep, will submit another PR to remove the now useless model file.

**Pull request merged**
