### PR TITLE
changes: update up to now

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
not final, just less work for later.

### CODE REVIEW

**Comment by selaux** [comment]
Cool, thanks.

**Comment by lynxlynxlynx** [comment]
Yeah, as it also serves as a reminder.

**Comment by selaux** [comment]
Updated to current status.

**Comment by lynxlynxlynx** [comment]
I could swear I saw your commit somewhere — why doesn't it show up here?

**Comment by selaux** [comment]
I squashed it into yours :smile:

**Pull request merged**
