### PR TITLE
enhancement: Quit the Game from Main Screen on CTRL-Q / CTRL-ESC

### PR DESCRIPTION
**Pull request by misanthropos**
Signed-off-by: Richard Fröhning <misanthropos@gmx.de>

### CODE REVIEW

**Comment by ja2-derek** [comment]
Looking back in git-blame, it has been disabled since the initial import 18 years ago.

I have a habit of tapping `Esc` repeatedly on game launch, to skip the SirTech logo animation intro. I will for sure quit the game unexpectedly.

**Comment by lynxlynxlynx** [comment]
We should also have a skip_intro_videos settings key, so we don't even try loading them, obviating the need for skipping.

To prevent accidental escaping on entry, we can use a timer and only process esc in the main menu if at least, let's say, 2 seconds have passed since it was loaded.

**Comment by misanthropos** [comment]
> We should also have a skip_intro_videos settings key, so we don't even try loading them, obviating the need for skipping.
> 
https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1738

**Comment by momoko-h** [comment]
How about changing that line to
 ```case SDLK_ESCAPE: if (GetJA2Clock() >= 30000) gbHandledMainMenu = QUIT; break;```

Then the ESC key would be enabled 30 seconds after the game started.

**Comment by misanthropos** [comment]
> How about changing that line to `case SDLK_ESCAPE: if (GetJA2Clock() >= 30000) gbHandledMainMenu = QUIT; break;`
> 
> Then the ESC key would be enabled 30 seconds after the game started.

I changed it to CTRL-ESC as a compromise.

**Comment by lynxlynxlynx** [comment]
Nobody will think of ctrl-esc.

**Comment by misanthropos** [comment]
> Nobody will think of ctrl-esc.

Agreed - I added CTRL-Q in addition.

**Comment by lynxlynxlynx** [comment]
I don't think that's any better; anything hidden behind a modifier just won't come up.

**Comment by misanthropos** [comment]
> I don't think that's any better; anything hidden behind a modifier just won't come up.

To me CTRL-q comes naturally. Another idea could be to empty the input event queue before leaving intro and going back to ESC.

**Review by momoko-h — CHANGES_REQUESTED** [review]
Some bits of nitpicking:

- there is no need to keep these remnants of the game's Windows-only past around
- the function name and what it actually does do not match
- The other use of this function in `LoadWorldFromSGPFile` should probably be removed. If we did not need to drop events there before we won't need it now either.

**Comment by misanthropos** [comment]
> 
>     * there is no need to keep these remnants of the game's Windows-only past around

which remnants?

> 
>     * the function name and what it actually does do not match

can you please be more specific?

> 
>     * The other use of this function in `LoadWorldFromSGPFile` should probably be removed. If we did not need to drop events there before we won't need it now either.

This would be a cleanup for something else?

**Comment by misanthropos** [comment]
damn i just committed to master. If thats is ok I wont revert it.

**Comment by momoko-h** [comment]
> > ```
> > * there is no need to keep these remnants of the game's Windows-only past around
> > ```
> 
> which remnants?

The part you commented out, the MSG definition and the  PeekMessage call. Those are parts of the Windows API.
> > * the function name and what it actually does do not match
> 
> can you please be more specific? So I should rename it to DequeueAllEvents?

Yes.
> 
> > ```
> > * The other use of this function in `LoadWorldFromSGPFile` should probably be removed. If we did not need to drop events there before we won't need it now either.
> > ```
> 
> This would be a cleanup for something else?

A new PR just to remove one line?

**Comment by misanthropos** [comment]
Does it hurt to leave it?

**Comment by momoko-h** [comment]
Loading a game is so fast nowadays that there won't be many events to dequeue anyway. And if someone knows beforehand that they want to select a certain merc or squad and presses the key for it while the loading screen is still up, why shouldn't they be able to do that? It has worked until now. 

I just dislike it in general when software ignores my input.

**Comment by misanthropos** [comment]
Since it seemed to have had no side effects until reactivating DequeueAllEvents I don´t object on removing that from LoadWorldFromSGPFile - But it was the original intention to not do that (press keys before game is ready).

**Pull request closed without merging**
