### PR TITLE
use stable version of getopts

### PR DESCRIPTION
**Pull request by MeisterP**

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Is this version something newer than the revision we used?

**Comment by selaux** [comment]
Yep.

**Comment by Manuel-K** [comment]
@lynxlynxlynx Yes. The specific revision that we use is from July. 0.2.15 was released in September.

**Comment by Manuel-K** [comment]
@selaux Dirty ninja. ;-)

**Comment by selaux** [comment]
@MeisterP Thx for the PR 🙂 .

@Manuel-K Hehe

**Pull request merged**
