### PR TITLE
Fixed getopts dependency rev

### PR DESCRIPTION
**Pull request by selaux**

### CODE REVIEW

**Comment by Manuel-K** [comment]
Is it possible to set a minimal rev? Note: I've made the assumption that this fixes a specific rev.

**Comment by selaux** [comment]
Here you go 🙂

**Comment by Manuel-K** [comment]
Note: this is related to #562

**Comment by Manuel-K** [comment]
It seems it is not possible. 

From http://doc.crates.io/specifying-dependencies.html:

> Since we haven’t specified any other information, Cargo assumes that we intend to use the latest commit on the master branch to build our project. You can combine the git key with the rev, tag, or branch keys to specify something else. Here's an example of specifying that you want to use the latest commit on a branch named next:

**Comment by lynxlynxlynx** [comment]
we can bump it manually, as it's not likely that it will be needed often.

**Comment by selaux** [comment]
@Manuel-K What seems to not work?

**Comment by lynxlynxlynx** [comment]
I think he meant an open interval, a minimum version vs a fixed revision/tag.

**Comment by selaux** [comment]
Ah ok, I overread the minimal part

**Pull request merged**
