### PR TITLE
Create temporary UINT16 variables when saving/loading

### PR DESCRIPTION
**Pull request by selaux**
My try at fixing #328. Lets see if it works (last commit actually implements the change).

### CODE REVIEW

**Comment by derSteFfi** [comment]
that's much cleaner. +1 :)

**Comment by selaux** [comment]
Is this good to merge? Not sure if anybody tested, but should be non critical :wink:

**Comment by lynxlynxlynx** [comment]
Not me, but let's just do it the python way.

**Comment by selaux** [comment]
What is the python way?

**Comment by lynxlynxlynx** [comment]
Ask forgiveness not permission. :)

**Pull request merged**
