### PR TITLE
Update rust toolchain to 1.36.0

### PR DESCRIPTION
**Pull request by flaviojs**
Originally I was updating to 1.34.0 for `SlfEntry::to_system_time` but it came with new warnings.
There is no reason to aim for a low version (not a library).
Since new warnings are unavoidable, I updated to the latest stable version.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
1.34 is the latest on ubuntu 18.10, so I don't think we should go higher yet — just making it harder for people to build.

**Comment by flaviojs** [comment]
Version 18.10 is no longer supported by ubuntu, maybe that's why the rust version is older than the supported releases.

**Comment by flaviojs** [comment]
All the releases supported by ubuntu have version 1.36 or 1.37 and the clippy in version 1.34 has issues.

@lynxlynxlynx Is 1.36 good enough?

**Comment by lynxlynxlynx** [comment]
Yep, that's present in ubuntu.

**Pull request merged**
