### PR TITLE
Only do unicode normalization on strings where it is necessary

### PR DESCRIPTION
**Pull request by selaux**
See  #1268

### CODE REVIEW

**Comment by ja2-derek** [comment]
Thanks! For me, it halved the latency, from 60ms to about 30ms. It is a good improvement. `default_case_fold` might account for the remaining half of the time spent.  

With a naive string-to-lower, the latency can be down to 1ms or less.

**Comment by ja2-derek** [comment]
How about checking [is_ascii](https://doc.rust-lang.org/std/string/struct.String.html#method.is_ascii), and then do the naive `to_ascii_lowercase`? I believe this can optimize the performance for 99% of the cases.

**Comment by selaux** [comment]
Added to_ascii_lowercase. I'd still not close #1268 though. I would still want to check how it behaves on a HDD instead of an SSD, as there listing directories might be the slowest part.

**Comment by ja2-derek** [comment]
Great! It is now down to 1ms!

**Comment by selaux** [comment]
Yeah I actually was thinking about the same (cache), but lets optimize all the acesses first and then check how fast we are. Maybe we can avoid caching...

**Pull request merged**
