### PR TITLE
integrate gui_extras

### PR DESCRIPTION
**Pull request by derSteFfi**
as previously done by vxx and 1.13, switchable via gui_extras in game.json

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
It would be cleaner if everything used the progress variant and then it checked for the presence of the flag.

Also, looks like a candidate for further refactoring, since the stat blocks are practically identical.

**Comment by RinneT** [comment]
Looks interesting, do you have more specific info on what it does?

Also: I may be stupid but I can't seem to find it on my git. git fetch origin doesn't add it to my branch list.
Any input on what I'm doing wrong? Kind of new to all the git stuff (though I love it).

**Comment by derSteFfi** [comment]
@lynxlynxlynx you're right. I'll change that as soon as I get ot it.

**Comment by lynxlynxlynx** [comment]
What about the same in Build/Tactical/Interface_Panels.cc? It also looks like the PrintStat function could be shared.

**Comment by derSteFfi** [comment]
i refactored it for the start. I'll try to use the One from Tactical in Map_screen now

**Comment by derSteFfi** [comment]
So, not that easy. The handling of the coordinates is different. In Tactical, the coordinates point to the start of the short string for each stat (STR, AGI, ...) in Strategic it's the start of the actual value. Cleaning this up would be quite messy I guess because one would need to adapt the drawing of all strings for one of both...

**Pull request merged**
