### PR TITLE
Fixes Stealing AP Bug

### LINKED ISSUE #191: Mysteriously disappearing APs when stealing
Originally reported by: **Agatae Tsag (Bitbucket: [Agatae](http://bitbucket.org/Agatae), GitHub: Unknown)**

---

In the attached save Johny can steal enemies weapon. It costs 10 APs to do so. However, after he does so he looses another 5 AP.
He can attack first and steal later. Then the mysterious loss drops him to 0, taking 'just' 3 APs.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/191

### PR DESCRIPTION
**Pull request by daviel**
Fixes #191 
For some reason someone put the condition in comments. Can't tell why. Normal Hand to hand still works as aspected with the condition.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
you can use `git blame filename` to see who last changed each line, with which commit (hash). Then `git show commit-hash`. Its message may have a reason (like a different bug) or you just may end up at the end of history — when the code was first released.

**Comment by daviel** [comment]
It's telling me that this line was last changed on initial import(Sep 6 2004). So the reason stays unknown.

**Comment by lynxlynxlynx** [comment]
Great, thanks!

**Comment by Manuel-K** [comment]
Check indentation after #556 is merged.

**Pull request merged**
