### PR TITLE
Fix #540: always show militia dialogues in the same spot

### LINKED ISSUE #540: Maximum militia Message at the wrong position
This is probably also related to higher resolution but this just happened:
screenshot_20170606_031217

The savegame is [here](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1053547/QuickSave.zip). Just let the time continue until 6:00 AM and you get that error. What happens is that two teams finish their task of training militia, but one team cannot continue (max militia).

### PR DESCRIPTION
**Pull request by derSteFfi**
inline the remaining one line function for the sake of clarity

### CODE REVIEW

**Comment by Manuel-K** [comment]
Echoing the issue number because github ignores the title: #540

**Comment by lynxlynxlynx** [comment]
LGTM here too, but haven't tested. I'm fine with the design decision though.

**Comment by Manuel-K** [comment]
I've tested the changes using the provided savegame.

**Comment by lynxlynxlynx** [comment]
yay, team work. :)

**Pull request merged**
