### PR TITLE
Cleanup turnbased

### PR DESCRIPTION
**Pull request by Manuel-K**
Remove `TURNBASED` checks.

Might be incomplete and have errors.

Went through the code once while waiting for dinner.

### CODE REVIEW

**Comment by chmallon** [comment]
The check in `HandleMoveModeInteractiveClick()` was always false in vanilla.
With this change this is not the case anymore.

**Comment by Manuel-K** [comment]
Fixed.

**Comment by lynxlynxlynx** [comment]
Is this still WIP? Besides whitespace, it looks ok, but I haven't checked if you missed any remaining uses.

**Comment by Manuel-K** [comment]
Good question. I remember `grep`ing for missed instances. I'll re-check tomorrow.

**Comment by Manuel-K** [comment]
```
[src]$ grep TURNBASED -r --color .
./game/Tactical/Overhead_Types.h:#define TURNBASED                                      0x000000004
./game/Tactical/Overhead.cc:    t.uiFlags                 = TURNBASED;
./game/TacticalAI/AIList.cc: * (in TURNBASED COMBAT) keeps track of which AI guy should
```

Seems to be gone.

**Comment by lynxlynxlynx** [comment]
So why the first two matches, savegame compatibility?

**Comment by Manuel-K** [comment]
That was the initial idea, but I'm not sure if I checked if it gets saved.

**Comment by Manuel-K** [comment]
Yes, it does get saved.

`INJ_U32(d, s->uiFlags)` in `InjectTacticalStatusTypeIntoFile(HWFILE const f)` in `src/game/LoadSaveTacticalStatusType.cc`.

**Comment by lynxlynxlynx** [comment]
I guess it can't hurt and could be handy for bisecting with newer saves. Didn't check if the Overhead setting happens before loading a game, but it's likely.

**Comment by Manuel-K** [comment]
We could inline it, e.g.:
`t.uiFlags                 = 0x000000004: // == TURNBASED for save game compatibility`

**Comment by lynxlynxlynx** [comment]
Don't care either way. Ready for merge if you ask me.

**Comment by lynxlynxlynx** [comment]
So ... want to do the same for REALTIME?

**Comment by Manuel-K** [comment]
It seems that REALTIME is never set, correct? It is unset once in `game/Editor/EditScreen.cc`.

I've `grep -G`ed  for `uiFlags.*REALTIME` and for `uiFlags.*2`.

**Comment by lynxlynxlynx** [comment]
Yes, useless. I was checking via:

> ggn =.*REALTIME[^_]
> ggn =.*IN_RT_COMBAT

**Comment by Manuel-K** [comment]
I've already removed IN_RT_COMBAT because it wasn't used anywhere.

**Pull request merged**
