### PR TITLE
Create ja2-launcher.log in temp directory

### PR DESCRIPTION
**Pull request by ja2-derek**
For #1257, see also https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1335#issuecomment-795058271.

We have changed log location of the main process. This updates the same for the `ja2-launcher`.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
I guess gcc9 needs to be installed explicitly?

**Comment by ja2-derek** [comment]
> I guess gcc9 needs to be installed explicitly?

No, image has gcc/g++ both 7.5 and 9.0 installed already - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md

**Comment by ja2-derek** [comment]
The MingW build is still on Ubuntu 18.04, in which [gcc-mingw-w64-x86-64](https://packages.ubuntu.com/bionic/gcc-mingw-w64-x86-64) is at v7.3, and do not have the `std::filesystem`.

There is a problem with building with newer the MingW [package](https://packages.ubuntu.com/focal/gcc-mingw-w64-x86-64) in Ubuntu 20.04. Later on when we get that sorted, we can clean up all usages of `std::experimental::filesystem`.

**Comment by selaux** [comment]
Thanks for the PR and fighting the builds 😉 .

**Pull request merged**
