### PR TITLE
Update boost to 1.61.

### PR DESCRIPTION
**Pull request by selaux**
Still a lot of changes, but should be better than last one.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
go for it, once travis is happy. I guess the project just grew so much in the meanwhile, that it's still almost a doubling of included code?

**Comment by selaux** [comment]
Seems like it, it's also hard to find out which headers actually are used, so there are probably more headers included than necessary.

**Comment by lynxlynxlynx** [comment]
I think I used cppclean for that before, but it was pretty noisy. Doing a quick search this popped up, but I haven't used it, so no idea if it's any better or worse: https://sourceforge.net/projects/chksem/

**Comment by selaux** [comment]
I could not find anything that does what I want so I created a small python script: https://gist.github.com/selaux/f1eb93fde855ed12ac6973171da1ae56

The added/removed lines ratio looks much better now.

**Comment by lynxlynxlynx** [comment]
Nice, now it's a significant reduction.

**Pull request merged**
