### PR TITLE
Fix #201: Add coverity testing via coverity-via-travis branch.

### LINKED ISSUE #201: Figure out what to do with Coverity testing
Originally reported by: **Jaka Kranjc (Bitbucket: [jaka_kranjc](http://bitbucket.org/jaka_kranjc), GitHub: Unknown)**

----------------------------------------

As you may know, Coverity provides a static code analyzer, free for open source projects. Apparently the SFI license is not too dodgy for them and one fork of this repo is already using it:
https://scan.coverity.com/projects/ja2-stracciatella

Since it's from an inactive fork, it's not tracking upstream - this repo - and so can't be used to detect regressions quickly. (Cov can actually be integrated with Travis). The past fixes have hopefully already made it here.

I suggest the author be contacted and the source url changed to this repo.

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/201

### PR DESCRIPTION
**Pull request by selaux**
This allows us to run a coverity scan every time the coverity-via-travis branch is updated. We should merge this into master though, so we can simply create a PR from master to this branch to get a fresh build. I'm currently waiting for the first build to complete to see if everything works.

We could also create a bot that does that every week.

### CODE REVIEW

**Comment by derSteFfi** [comment]
why not simply run a scan everytime master changes? Are the scans very extensive?

**Comment by selaux** [comment]
They have a limit of I think 1 run per week.

**Comment by lynxlynxlynx** [comment]
It used to be one per day, but they upped it about half a year ago. Still, I agree the branch approach is better. We don't need it for every single commit.

**Comment by lynxlynxlynx** [comment]
Did you set up the coverity account yet? Agatae responded now ...

**Comment by selaux** [comment]
Yes, it is accessible here: https://scan.coverity.com/projects/ja2-stracciatella-ja2-stracciatella?tab=overview

**Comment by selaux** [comment]
Or should we add a team account (for which we need a team email).

**Comment by lynxlynxlynx** [comment]
You don't need a team account for multiple people to have access. All get mailed on failures too.

**Comment by selaux** [comment]
Can you somehow try to join the team and then I will add you as owner (I cannot invite you since I dont know your email address). @derSteFfi already did this.

**Pull request merged**
