### PR TITLE
WIP: added Chinese translation #810

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
@ChinaSakhalin provided a basic translation in #810 and I've made all the fixes and code adjustments necessary for it to run via ` ./ja2 -resversion CHINESE` (or the launcher).

There are a few TODOs sprinkled inside, just as a reminder, since I don't have the data or font to fully test. But yes, this is useless without a font, while modified data (STIs) would also make it better.

But apparently the existing font is useless, 1.13 implemented winfont support instead. [JA2.v1.13-4452.sourcecode.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3051039/JA2.v1.13-4452.sourcecode.zip)

### CODE REVIEW

**Comment by flaviojs** [comment]
Hmm, wouldn't this chinese translation be better off as a mod instead of a new resversion?

**Comment by lynxlynxlynx** [comment]
I don't see how that could work; depending on the way it is done, it may need a mod on top either way.

**Comment by flaviojs** [comment]
The `-resversion` option tells stracciatella the language of the game data and what to emulate.
This chinese translation is not a direct modification of the original data, but a translation on top of the original data so stracciatella should still try to emulate the original (whatever version that is).

The main problem is the fonts, we have glyph images but no unicode codepoint<->glyph mappings.
The translation table would need to be externalized or real fonts supported (they include mappings).
Translation tables need to be specific to each font (or glyph count), as you can see in issue #837.

**Comment by flaviojs** [comment]
Closed by mistake when I used push instead of pull. >.<

**Comment by lynxlynxlynx** [comment]
Closing in favour of #1445.

**Pull request closed without merging**
