### PR TITLE
Config var for scaling website loading time on laptop

### PR DESCRIPTION
**Pull request by FluffyQuack**
Adds "website_loading_speed_scale" config var for scaling the speed of loading time of websites on the laptop.

### CODE REVIEW

**Comment by ja2-derek** [comment]
Minor nitpick - I think it is scaling the loading time rather speed? I got a little confused reading the json comments. 

Maybe we can just say something like higher value means longer load time.

**Comment by FluffyQuack** [comment]
> Minor nitpick - I think it is scaling the loading time rather than speed? I got a little confused reading the json comments.
> 
> Maybe we can just say something like higher value means longer load time.

Just committed a change that renamed the variable and changed the comments to make it clearer what it does.

**Comment by lynxlynxlynx** [comment]
Thanks! Not sure why the needless whitespace change at the last minute though — try to refrain from that.

**Comment by FluffyQuack** [comment]
> Thanks! Not sure why the needless whitespace change at the last minute though — try to refrain from that.

Oh, sorry, I didn't even notice that happened, and I'm not sure how it happened. I edited game.json using notepad++ but I didn't expect that to result in a formating change.

**Pull request merged**
