### PR TITLE
Tactical AI fixes

### PR DESCRIPTION
**Pull request by ja2-derek**
Including the simple and (seemingly) straight-forward fixes as suggested in #1384, #1385 and #1388. May add more commits if we have more of the bugs.

I propose to gate all these bug-fixes (together with #1281) behind one option in `game.json`. Defaults to enabled, but it can still be disabled to allow a true "vanilla" (and buggy) experience.

I plan to do a play-through with all fixes enabled, and see how it goes. I don't really have a systematic way to verify the AI fixes.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
You can use the existing main ai key, since that was added in a similar situation.

**Comment by ja2-derek** [comment]
I have played for some time with the fixes. I don't notice anything changed, but that doesn't break anything either.

As you can see these fixes some obvious coding errors, I think we can just apply them directly.

**Comment by selaux** [comment]
:+1: Sounds good to me.

**Comment by ja2-derek** [comment]
New defects reported by Coverity - 

```
*** CID 240335:  Code maintainability issues  (UNUSED_VALUE)
/home/runner/work/ja2-stracciatella/ja2-stracciatella/src/game/TacticalAI/FindLocations.cc: 1627 in SearchForItems(SOLDIERTYPE &, ItemSearchReason, unsigned short)()
1621     							{
1622     								INT8 const new_rating = EffectiveArmour(&o);
1623     								INT8 current_rating = EffectiveArmour(&cur_armour);
1624     								if (current_rating >= new_rating) continue; // the new armour isn't better, skip
1625     								if (current_rating == 0) current_rating = 1; // avoid division by zero
1626     
>>>     CID 240335:  Code maintainability issues  (UNUSED_VALUE)
>>>     Assigning value from "100 * new_rating / current_rating" to "temp_value" here, but that stored value is overwritten before it can be used.
1627     								temp_value = 100 * new_rating / current_rating;
1628     							}
1629     						}
1630     						/* FALLTHROUGH */
1631     
1632     					case SEARCH_WEAPONS:
```

**Pull request merged**
