### PR TITLE
Update rapidjson to 1.1.0 and add comments to game.json

### PR DESCRIPTION
**Pull request by selaux**

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks good, but I can't test it. So if it works, I'd just merge it.

**Comment by lynxlynxlynx** [comment]
I'm back and this works fine. :)
Note to people running it from the build dir - edit the game.json in this one's externalised dir, not the source one.

**Comment by selaux** [comment]
Hm, it should copy the externalized dir on build but maybe that does not work as expected.

**Comment by lynxlynxlynx** [comment]
it does, but if you edit the source after that, it can't have an effect.

**Pull request merged**
