### PR TITLE
Appending extra game states at the end of Saves

### PR DESCRIPTION
**Pull request by ja2-derek**
Providing the basis for #1272.

## Summary

- Renamed `GameState` to `GameMode`, because the class has nothing to do with the current state of the game
- Game save version incremented from `100` to `101`
- Saved game is compatible with current master (Not yet tested with base vanilla)
- Extra key-value data is appended to the end of the save
- Key are strings; Values are `std::variant`, can be any one of  primitives (`int32_t`, `float`, `bool` and `string`) or, a map or vector of primitives.

## Usage

It is accessed via the `g_gameStates` in SaveLoadGameStates.h.

- Loading a primitive value (one of `int32_t`, `bool`, `ST::string` or `float`)
```c
#include "SaveLoadGameStates.h"

INT32 intval = g_gameStates.Get<INT32>("key1");
ST::string st = g_gameStates.Get<ST::string>("key2");
```
- Saving a typed container 
```c
#include "SaveLoadGameStates.h"

std::map<ST::string, INT32> intmap = g_gameStates.GetMap<INT32>("some-key");
g_gameStates.SetMap<INT32>("some-key", intmap);

std::vector<ST::string> strings = g_gameStates.GetVector<ST::string>("my-strings");
g_gameStates.SetVector<ST::string>("my-strings", strings);
```
- Using saved game states from Lua
```lua
function handle_before_game_saved()
  local states = {
    what_happened = "nothing"
  }
  PutGameStates("my-awesome-mod", states)
end

function handle_on_game_loaded()
  local states = GetGameStates("my-awesome-mod")
  log.info(states.what_happended)
end
```

## Details

With this PR, loading saves across versions will give the "load an older version save" prompt. Nothing uses the states yet, so it will always write `2;{}` (data length and then the JSON data, in binary).

~The usage of VARIANT should match `std::variant` in C++ 17, so we can migrate later on~. Although the values are variant, we still need to pre-determine the keys and type to make use of them. But JSON and variant serialization should be good for future extensions. 

Data is written as raw JSON and not compressed. Even in plain text it is not that big, and if we were to compress, we should layer it over the whole file.

------

Could you please review and give me some feedbacks? If it is OK, we can start talking about what data can be included - e.g. states from mod scripts, list of mod names the game was started with.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks fine to me.

Ideally we'd store the used mod list here and ensure they're loaded, so the choices at game/launcher startup aren't important. I think our VFS can handle that. Would also mean that we don't need to have per-mod save dirs, but for that also #823 is important. And we could improve the save game list display to also show this mod info.

**Comment by selaux** [comment]
Looks good to me as well. It would be nice to be able to store lists (`std::vector`) and maps (`std::map`) in there as well. Would that be possible with the variant approach?

**Comment by ja2-derek** [comment]
Thank you guys.

Given that C++ is static-typed, we can support vectors and maps of primitives with templates/generics, but not anything nested. And we still need to pre-determine the allowed types in `std::variant` and then implement all (de-)serialization with RapidJSON. I don't see any blocking issues with that.

Re C++ 17, I can try to make the switch, but as I remember there are some warnings or errors with RapidJSON, which hasn't had a formal release since 2016.

**Comment by ja2-derek** [comment]
`std::variant`, `std::vector` and `std::map` for primitive types are done.

**Comment by lynxlynxlynx** [comment]
Is this indeed still a draft?

**Comment by ja2-derek** [comment]
I don't have anything to add to this PR. I hesitate to get this merged because it introduce a save game format break without adding any real value to the vanilla game play.

My original plan was to incorporate this in my Unfinished Business mod work before merging. However I don't have much progress in the UB support lately.

**Comment by lynxlynxlynx** [comment]
Hmm, ok. I don't want it to needlessly bit rot, but it sounds like we should wait for some work that needs it or maybe do it right after a release.

**Comment by ja2-derek** [comment]
The branch was rebased to resolve a merge conflict. Only these two commits are new 774359f and 38349b0 .

I am going to verify the save game compatibility with 0.18. After that this should be good for merge.

**Comment by ja2-derek** [comment]
Tested the save game compatibility, both forward and backwards, between 0.18 and master, also between vanilla (1.12 GOG) and master. In all cases it prompts "Attempting to load an older version save..." even when the save is made by the newer version.

**Comment by lynxlynxlynx** [comment]
Reread the diffs and all looks fine to me. 👍🏾

**Pull request merged**
