### PR TITLE
SDL2 2.0.6 Warnings

### PR DESCRIPTION
**Pull request by Manuel-K**
Fix (or rather workaround) for #608 

- [x] Disable sound if version 2.0.6 is detected at runtime
- [x] Print error message to console and log file
- [x] Display warning in main menu
- [x] Add warning to `COMPILATION.md`

### CODE REVIEW

**Comment by selaux** [comment]
Added note to `COMPILATION.md`

**Comment by Manuel-K** [comment]
It is definitely a run time issue not a compile time issue. Perhaps it would be better to change the `compile with a different version` to `run the game with a different version`.

**Comment by selaux** [comment]
👍 Fixed, will merge when builds succeed...

**Comment by Manuel-K** [comment]
Erster ;-)

**Pull request merged**
