### PR TITLE
Add LRU cache for directory listings in canonicalize

### PR DESCRIPTION
**Pull request by selaux**
This implements a caching layer for file path canonicalization in the VFS. Basically it cached all `fs::read_dir`/`android::list_asset_dir` calls in their original and NFC variant. I decided to cache the listings and not actually the resolved files, as with a single `read_dir` this allows us to resolve multiple files via cache already.

For me this reduces the time to read a file from ~100000ns to ~5000ns (given the cache has been filled to an extent).

@ja2-derek Can you test this as well and let me know how much that improves the situation for you?

NB: One thing I'm not quite sure about yet is the `Temp/` dir within the `Data` dir. I still have to find out what exactly is written there and why...That is why this is still a draft.

References #1268

### CODE REVIEW

**Comment by ja2-derek** [comment]
Briefly tested on my set up and it is in line with your results. The `VfsFile_open` used to take up to 3000 μs, and with this PR it is down to 100 μs. So with a squad of 6 soldiers, the improvement is ~20ms per click down to 0.6ms per click.

**Comment by selaux** [comment]
So this got bigger again. I cleaned up all the file accesses, because they were kind of a mess: Sometimes stuff was accessed using absolute paths, sometimes relative. Files in ja2 home were accessed using relative paths to the current working directory (e.g. `../ja2.set`). In this PR I introduced three ways to open files with associated sets of functions in the content manager:

- Private files (reside in the home directory)
- Temp files
- Resource files

This should make it easy to e.g. implement https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1255 in the future.

There are a big open question though: Previously when saving stuff in the editor it was going to the vanilla game directory. This seems wrong to me as the user probably does not want to overwrite vanilla stuff, but rather create a mod or something similar. How should we handle this? A few options come to mind:

- Store in the mod directory with highest priority
- Let the user choose freely where to store
- Store somewhere in home directory, so user can copy to mod

**Comment by lynxlynxlynx** [comment]
I propose two extra settings for the editor:
- boolean whether to save in the game dir, changing file directly, or a separate one
- file path for option 2, with a default to a new mod folder in the home directory

**Comment by lynxlynxlynx** [comment]
So, how much more is missing here?

**Comment by selaux** [comment]
I kind of got lost while implementing the editor changes.

I think I need to split this one up into:

- Making all file reads/writes happen through GCM
- Adding LRU cache

Some of the functionality in this PR has also already been introduced in master, so I have to merge them into these ones (e.g. https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1324). So this PR still has some way to go. Maybe I can find some time this week or next week to finalize.

**Comment by selaux** [comment]
Sorry I didn't get around to it yet. Too many merge conflicts, which need resolving...

**Comment by selaux** [comment]
Close in favor of https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1402

**Pull request closed without merging**
