### PR TITLE
Upload builds to google storage

### PR DESCRIPTION
**Pull request by selaux**
Should fix https://github.com/ja2-stracciatella/ja2-stracciatella/issues/873.

Not finished yet. But it is only testable using a PR...

### CODE REVIEW

**Comment by ja2-derek** [comment]
Is this something we can use? https://docs.travis-ci.com/user/deployment-v2/providers/gcs/

**Comment by selaux** [comment]
So I looked into this, but in the end it would be nice to end up with the same (or similar) code for all CI systems, so there is not so much duplication.

**Comment by lynxlynxlynx** [comment]
Is this now done?

**Comment by selaux** [comment]
No, I didn't get around to it yet.

**Comment by selaux** [comment]
It is done now: https://storage.googleapis.com/ja2-builds/index.html#pull-requests/1125/

**Comment by lynxlynxlynx** [comment]
Thanks!

**Pull request merged**
