### PR TITLE
Rework path finding estimates and increase path finding limits

### LINKED ISSUE #375: Incorrect tactical path calculation
[save.ZIP](https://github.com/ja2-stracciatella/ja2-stracciatella/files/465891/save.ZIP)
In the attatched save, if I try to move Johny 5 tiles north, the path is OK, takes 11 AP.
If I trye to move him 6 tiles north, the path is longer and takes 20 AP.

### LINKED ISSUE #678: "path blocked" - pathfinding on long distances
When trying to move your merc/squad over a very long distance in tactical view (eg to the delivery destination in Drassen Airport B13 while standing on the western edge of the map), the game fails to do so and gives a "path blocked" error message. It seems like the pathfinding is not calculated over long distances.
Can we do something about this limitation?

### PR DESCRIPTION
**Pull request by flaviojs**
Fixes #375
Fixes #678

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
LGTM, but requires testing.

**Comment by flaviojs** [comment]
Now it also fixes #678

**Comment by flaviojs** [comment]
While doing a test run I found it showing a different path while holding shift.
FindBestPath is called with the same arguments so this is weird...

[QuickSave.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3506803/QuickSave.sav.zip)
For me, when I point at the ground in front of Test (NW), it shows a path going around the bunker wall. If I hold shift it shows a path going over the bunker wall.

@lynxlynxlynx can you try this save with this PR and see if it's the same for you?

**Comment by flaviojs** [comment]
Never mind, it's actually a vanilla bug. Reported in #853.

**Comment by lynxlynxlynx** [comment]
Ah, the best kind of ask — self-resolving. :)

**Comment by flaviojs** [comment]
Played until I took over Drassen, nothing else was strange.

**Comment by lynxlynxlynx** [comment]
Excellent work again, thanks!

**Pull request merged**
