### PR TITLE
Fix creature town attack

### PR DESCRIPTION
**Pull request by ja2-derek**
Found bugs when investigating a [bug report](http://thepit.ja-galaxy-forum.com/index.php?t=msg&goto=360622&#msg_360622 ).

 - a67c898e6f54dad93d041acfe2051882f776ed35: `gubSectorIDOfCreatureAttack` is not correctly updated, which should mean all attacks will happen at the mine entrance sector. (Bug since #1106)
- fd2b3bea9431109329d7e779105c6898e6e68be1: `giLairID` never got reset during `ReStartingGame`. This seems to be an old issue (v0.16 or earlier). Loading a game with an active lair, then starting a new campaign game cause the next game to have the wrong `giLairID`, and this wrong ID will get saved.

Needs more testing, and further investigation to see if it is related to the reported bug.

### CODE REVIEW

**Comment by ja2-derek** [comment]
Tested the commits I made so far, and they should work as intended.

I don't have further findings on the bug report. We need further input from the reporter.

**Comment by ja2-derek** [comment]
I don't have anything to add for this. This PR is ready for review and merge.

I will continue investigation (and probably new PR) once the forum bug report has more updates.

**Comment by lynxlynxlynx** [comment]
Sent him a PM reminder, let's see ...

**Comment by ja2-derek** [comment]
Maybe should we merge the bug-fixes in this PR and go ahead with 0.17.0?

**Comment by lynxlynxlynx** [comment]
Agreed!

**Pull request merged**
