### PR TITLE
Reorganize rust

### PR DESCRIPTION
**Pull request by flaviojs**
Tasks:
-  [x] C code is contained inside module `c`
 - [x] figure out and fix dependencies of module `config`
 - [x] everything is formatted with rustfmt
 - [x] check formatting with travis/appveyor
 - [x] fix [clippy](https://github.com/rust-lang/rust-clippy) lints
 - [x] check clippy lints with travis/appveyor

Postponed:
 - split rust code into subcrates (lib, bin, C static lib)

A different PR:
- rename C functions

### CODE REVIEW

**Comment by selaux** [comment]
I started fixing clippy lints on a branch a few days ago: https://github.com/ja2-stracciatella/ja2-stracciatella/tree/clippy. We could merge it into this one...

**Comment by flaviojs** [comment]
Awesome. I merged the clippy branch. :)

**Comment by flaviojs** [comment]
Rebased onto master so it catches #856 and split my clippy fixes.

**Comment by flaviojs** [comment]
I decided not to try to split into subcrates until stable rust can discard subcrate stuff that isn't being used. I recall reading that nightly already does this so it's only a matter of time until stable does.

Not sure if I should rename C functions here or on a separate PR.
I want to use names similar to module `c::librarydb` for everything in the rust interface:
 - `LibraryDB_*`
 - `LibraryFile_*`

@lynxlynxlynx @selaux 
What do you guys think?

**Comment by lynxlynxlynx** [comment]
I don't care, as long as it is consistent. I'd be cool if we could run rustfm against PRs once these cleanups are done.

**Comment by flaviojs** [comment]
What happen to AppVeyor? Is there a way to trigger a build without a new commit?

**Comment by lynxlynxlynx** [comment]
Usually [ci skip] or [skip ci] work, but it will do it for both. 

Appveyor: can't you run the same pre-build stuff as for travis? We currently have nothing defined for that stage.

**Comment by selaux** [comment]
Shouldn't just adding `%USERPROFILE%\.cargo\bin` to the path before executing rustup work as printed on the [console](https://ci.appveyor.com/project/ja2-stracciatella/ja2-stracciatella/builds/27201963/job/s2ghoy2fdfvlgah6#L58)?

Regarding renaming im fine with doing it in a separate PR in order to keep refactorings as small as possible...

**Comment by selaux** [comment]
By the way: you all should have access to the project in appveyor if you sign in via GitHub...

**Comment by selaux** [comment]
And you could also check for clippy warnings in the CI. Just disable the ones that are currently not fixable in the respective module, see [the documentation](https://github.com/rust-lang/rust-clippy#allowingdenying-lints). That could also be a separate PR though...

**Comment by flaviojs** [comment]
Squashed those extra commits and added clippy lints to the build.

**Comment by flaviojs** [comment]
Done, thanks for the help. :)

**Pull request merged**
